### ISSUE TITLE
(null) value displaying on some of my calendar events

### ISSUE THREAD

**Issue by olliebaum** [JanBobolz/agendwatchfacePebble#1]
Hi, on my Android phone I'm subscribed directly to an ical calendar which when displayed on my pebble shows "(null)" on the second line of an event despite the fact that I have the [no text] option selected for the second line. (A "(null)" value is also displayed when I have the [location] text option selected and the event has no locations.) 

I have also subscribed to the same ical feed via Google Calendar and when AgendaWatchface is subscribed to the Google version of the calendar, it displays as expected and does not show the "(null)" value. 

I don't particularly want to use Google Calendar though because the feed takes a long time to sync which isn't suitable for the purpose that I had intended. Do you have any idea why this (null) value is showing and how I might go about clearing it? I've attached an image to show what I mean. 
Thanks,
Oliver.
![2014-07-19 17 40 17](https://cloud.githubusercontent.com/assets/4048746/3635212/8af0a2b6-0f63-11e4-8aaa-637194b35691.jpg)

**Comment by JanBobolz** [comment]
Very nice bug report! :) Thanks!

I think I pinned down the issue and fixed it in JanBobolz/agendawatchfaceAndroid@6bbc0a5af6e7fa0f98629230560455db8096d8f6

I'll release the next version on Google Play now, it'll be available in a few hours. Your issue _should_ be fixed then. However, I have no way to test that, so I'd be grateful if you'd report back!

**Comment by olliebaum** [comment]
Okay, cool. I will do. Thanks for the speedy response!

**Comment by olliebaum** [comment]
Awesome. Seems to be working perfectly now. Nice job on the inversion option too (I actually really like the orginal black text on white cards but it's nice to have the option to change).

**Comment by JanBobolz** [comment]
Great! Thanks for the feedback :)
