### ISSUE TITLE
Return long format of date when time header font is set to small

### ISSUE THREAD

**Issue by aeroechelon** [JanBobolz/agendwatchfacePebble#2]
Prior to some update, when setting the font size of the time to small, the weekday and month would be spelled in it's entirety. (e.g. Mon to Monday and Sept to September.)

Any chance to return this design choice?

**Comment by JanBobolz** [comment]
That was unintentional. It's fixed in e7f607e. I'll upload a new version to Google Play in a bit.

Thanks a lot for reporting! :)

**Comment by aeroechelon** [comment]
Awesome! Keep up the good work!
